language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
os:
  - linux
env:
  - DJANGO_VERSION=3.0.8
  - DJANGO_VERSION=2.2.6
  - DJANGO_VERSION=3.0.7
install:
  - pip install -q Django==$DJANGO_VERSION
  - pip install django_nose coverage>=5.0
  - pip install -r requirements.txt
script:
  - python3 manage.py test
