# Generated by Django 3.0.6 on 2020-05-31 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0001_Initial_Model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photograph',
            name='full_resolution_image',
            field=models.ImageField(blank=True, help_text='A full resolution copy of the image for close up looks', null=True, upload_to='images/fullres/%Y/%m/'),
        ),
    ]
