# Generated by Django 3.0.6 on 2020-05-14 13:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('equipment', '0001_Initial_Model'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lending',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_of_lending', models.DateField()),
                ('end_of_lending', models.DateField()),
                ('notes', models.TextField(blank=True, help_text='Additional notes on the process (Markdown supported)')),
                ('item_to_lend', models.ForeignKey(editable=False, help_text='The item to lend', on_delete=django.db.models.deletion.CASCADE, to='equipment.Item')),
                ('lending_user', models.ForeignKey(editable=False, help_text='The user who is lending the equipment.', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['start_of_lending'],
            },
        ),
    ]
