# Generated by Django 3.0.6 on 2020-05-14 13:24

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('equipment', '0001_Initial_Model'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applied_at', models.DateField(default=datetime.date.today, editable=False, help_text='Date of application')),
                ('declined', models.BooleanField(default=False, help_text="A declined application won't be deleted. Once an application was declined the user can't reapply. A declined application can be reenabled.")),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['declined', 'applied_at'],
            },
        ),
        migrations.CreateModel(
            name='PeerGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('notes', models.TextField(blank=True, help_text='Further description of the group. Markdown supported.')),
                ('created_at', models.DateField(default=datetime.date.today, editable=False, help_text='Date of creation')),
                ('visible_to_strangers', models.BooleanField(default=False, help_text='If true one can apply for becomming a member')),
                ('admins', models.ManyToManyField(related_name='admin_of_peergroups', to=settings.AUTH_USER_MODEL)),
                ('applications', models.ManyToManyField(through='peers.GroupApplication', to=settings.AUTH_USER_MODEL)),
                ('icon', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='equipment.Photograph')),
                ('members', models.ManyToManyField(related_name='member_of_peergroups', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name', 'created_at'],
            },
        ),
        migrations.AddField(
            model_name='groupapplication',
            name='application_for',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='peers.PeerGroup'),
        ),
        migrations.AddField(
            model_name='groupapplication',
            name='approved_by',
            field=models.ManyToManyField(help_text='Once all admins of a group approved the application, the last approving admin can fulfill it.', related_name='_groupapplication_approved_by_+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='groupapplication',
            name='declined_by',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
